build:
  tests:
    before:
      - cp .env.example .env
    override:
      - composer test:ci
      - php-scrutinizer-run
      - phpcs-run

  nodes:
    php71:
      environment:
        php: 7.1.3
        mysql: 5.5

    php72:
      environment:
        php: 7.2
        mysql: 5.6

    php73:
      environment:
        php: 7.3
        mysql: 5.7

    coverage:
      tests:
        override:
          - command: composer test:ci
            coverage:
              file: target/coverage.xml   # <- Set this to where we find the coverage data. The path is relative to the current directory.
              format: clover
    analysis:
      tests:
        override:
          - php-scrutinizer-run

filter:
  excluded_paths:
    - 'bootstrap/*'
    - 'public/*'
    - 'resources/*'
    - 'tests/*'
  dependency_paths:
    - 'vendor/*'


checks:
  php: true
  javascript: true


coding_style:
  php: {  }


tools:
# ...
