language: php

services:
  # 5.6.x by default
  - mysql

php:
  - 7.1.3
  - 7.2
  - 7.3

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - mysql -e 'CREATE DATABASE doika;'
  - nvm install 10

before_script:
  # disable xdebug if not coverage
  - if [[ $COVERAGE == "" ]]; then phpenv config-rm xdebug.ini; fi
  - cp .env.ci .env
  - composer install --no-progress --no-interaction --prefer-dist --no-suggest
  - php artisan key:generate
  - npm config set registry http://registry.npmjs.org/
  - npm install
  - npm run dev

script:  
  - composer test:ci
  - php artisan route:list
  - php artisan migrate:fresh --seed  

after_script:
  - |
    if [[ $COVERAGE == true && $TRAVIS_BRANCH == "master" ]]; then
      vendor/bin/phpunit --coverage-clover coverage.xml
      wget https://github.com/php-coveralls/php-coveralls/releases/download/v2.1.0/php-coveralls.phar
      php php-coveralls.phar --verbose
    fi

jobs:
  include:
    - stage: Release
      env:
        - BUILD=true
      script:
        - NAME="doika"
        - zip -r $NAME ./ -x .git/\* -x .github/\* -x .gitignore -x .travis.yml -x .editorconfig -x composer.json -x composer.lock -x node_modules/\*
        - TAG=$(git describe --tags)
        - FILE="./$NAME.zip"
        - if [[ -e $FILE ]]; then
          NEW_NAME="$NAME-$TAG.$TRAVIS_JOB_ID";
          mv $NAME.zip $NEW_NAME.zip;
          fi
      deploy:
        provider: releases
        api_key:
          secure: someinvalidkey
        file: "$NEW_NAME.zip"
        skip_cleanup: true
        on:
          tags: true
          repo: diglabby/doika
