language: php

php:
  - 7.1
  - 7.2
  - 7.3

before_script:
  - cp .env.ci .env
  - mysql -e 'create database doika;'
  - composer install --no-interaction --prefer-dist

script:
  - composer test:ci
